#161367442 API endpoint that rejects the requests
andela/taps-server pull request #15
Opened 2018-10-21 20:44 UTC by nouwatinjacob

#### What does this PR do?
Create an API endpoint that rejects the requests
#### Description of Task to be completed?
- delete all the requests that are rejected
#### How should this be manually tested?
- Clone this repo
- yarn install
- Add necessary env variable as specified in .env.sample
- yarn test
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#161367442](https://www.pivotaltracker.com/story/show/161367442)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2018-10-22 15:27 UTC, chidioguejiofor approved these changes

2018-10-23 12:32 UTC, Chieze-Franklin requested changes

2018-10-23 12:32 UTC, Chieze-Franklin commented on src/controllers/Requests.js
> +      return res.sendSuccess({ message: 'The request/requests has been successfully rejected' });
```suggestion
      return res.sendSuccess();
```

2018-10-23 12:57 UTC, Chieze-Franklin approved these changes

2018-10-23 12:57 UTC, merged